字段设置案例：
{
	"field": "componentid",			//字段标识
	"itemname": "组件id",			//字段名称(显示有页面)
	"type": "int",					//数据表中数据类型
	"maxlength": "10",				//字段最大长度
	"isnull": true,					//数据表中是否允许为null
	"islist": 列表名称,				//数据表中值是否为列表(如果是列表，其值为列表名称；否则为空)
	"default": 0,					//字段默认值
	"effect": "",					//作用于表，可选值main(itemnamet和islist项同时作用于主表）|""(默认附加表) | "tab_表名"（各项属性适用于对应名称的表）
	"fieldget": 1,					//是否采集数据（如果设置1，则在视图输出该字段的输入框；返回之不输出。）
	"fieldset": 1,					//是否写入数据（如果设置1，则在model中获取客户后台客户端采集到的数据，将其保存到数据库中；返回之不保存。）
	"limit": 4,						//限制图片上传的张数，或限制address的层级数
	"novaild": 1,					//如果为true，对字段不需要特殊字符过滤
	"inputtype":"input",			//输入框类型 input|checkbox|radio|select|textarea|uediter|uploader|nesmodal|address|freemodal
	"attr": " disabled data-def=4 data-comment=如：这是注释" //视图中输入框属性
}
关于 输入框类型的说明：
 input：
 checkbox: 
 radio:
 select:
 textarea:
 uediter:	
 uploader: 上传图片控件
 nesmodal: 是modal(模态框)与nestable 结相结和的输入对话框
 address：联动地址模块
 freemodal: 自定义模态框
 
 


//youbang_addoninfos 表字自动填充字段配置信息：(当前与表一致)
[
  {
    "field": "classify",
    "itemname": "所属分类",
    "type": "text",
	"effect": "main",
    "maxlength": "1024",
    "isnull": true,
    "islist": "工程信息分类",
    "default": 0,
    "fieldget": 0,
    "fieldset": 0,
    "inputtype": "nesmodal",
    "attr": " disabled data-def=4 data-comment=如：这是注释"
  },
  {
    "field": "componentid",
    "itemname": "组件id",
    "type": "int",
    "maxlength": "10",
    "isnull": true,
    "islist": "",
    "default": 0,
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": " disabled data-def=4 data-comment=如：这是注释"
  },
  {
    "field": "title",
    "itemname": "标题",
    "type": "varchar",
    "maxlength": "72",
    "isnull": false,
    "islist": "",
    "default": "",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": " disabled data-def=4 data-comment=标题长度最多15个字符"
  },
  {
    "field": "litpic",
    "itemname": "缩略图",
    "type": "varchar",
    "maxlength": "255",
    "isnull": true,
    "islist": "",
    "default": "",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": " disabled data-def=4 data-comment=标题长度最多15个字符"
  },
  {
    "field": "arcrank",
    "itemname": "受权浏览",
    "type": "int",
    "maxlength": "5",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "radio",
    "attr": "type=number checked disabled"
  },
  {
    "field": "mid",
    "itemname": "会员id",
    "type": "int",
    "maxlength": "8",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=number disabled "
  },
  {
    "field": "click",
    "itemname": "点击",
    "type": "int",
    "maxlength": "10",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=number disabled "
  },
  {
    "field": "userip",
    "itemname": "会员IP",
    "type": "text",
    "maxlength": "15",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=text disabled"
  },
  {
    "field": "senddate",
    "itemname": "发布时间",
    "type": "int",
    "maxlength": "10",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=date"
  },
  {
    "field": "flag",
    "itemname": "推荐属性",
    "type": "checkbox",
    "maxlength": "10",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "checkbox",
    "attr": "type=checkbox data-key=c-h-z-r data-val=推荐-首页-资讯-热点"
  },
  {
    "field": "lastpost",
    "itemname": "最后评论时间",
    "type": "int",
    "maxlength": "10",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 0,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=text disabled"
  },
  {
    "field": "scores",
    "itemname": "评论积分",
    "type": "int",
    "maxlength": "8",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=number disabled"
  },
  {
    "field": "goodpost",
    "itemname": "好评数",
    "type": "int",
    "maxlength": "8",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=number disabled"
  },
  {
    "field": "badpost",
    "itemname": "差评数",
    "type": "int",
    "maxlength": "8",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=number disabled"
  },
  {
    "field": "nativeplace",
    "itemname": "地区",
    "type": "stepselect",
    "maxlength": "250",
    "isnull": "true",
    "islist": "",
    "default": "0",
    "fieldget": 1,
    "fieldset": 1,
	"limit": 2,
    "inputtype": "address",
    "attr": ""
  },
  {
    "field": "infotype",
    "itemname": "信息类型",
    "type": "stepselect",
    "maxlength": "250",
    "isnull": "true",
    "islist": "信息类型",
    "default": "0",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "nesmodal",
    "attr": ""
  },
  {
    "field": "body",
    "itemname": "信息内容",
    "type": "htmltext",
    "maxlength": "250",
    "isnull": "true",
    "islist": "",
    "default": "",
    "fieldget": 1,
    "fieldset": 1,
    "novaild": 1,
    "inputtype": "uediter",
    "attr": "type=text"
  },
  {
    "field": "endtime",
    "itemname": "截止日期",
    "type": "datetime",
    "maxlength": "250",
    "isnull": "true",
    "islist": "",
    "default": "",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=date"
  },
  {
    "field": "tel",
    "itemname": "联系电话",
    "type": "text",
    "maxlength": "50",
    "isnull": "true",
    "islist": "",
    "default": "",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=tel"
  },
  {
    "field": "email",
    "itemname": "电子邮箱",
    "type": "text",
    "maxlength": "50",
    "isnull": "true",
    "islist": "",
    "default": "",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=email"
  },
  {
    "field": "linkman",
    "itemname": "联系人",
    "type": "text",
    "maxlength": "50",
    "isnull": "true",
    "islist": "",
    "default": "",
    "fieldget": 1,
    "fieldset": 1,
    "inputtype": "input",
    "attr": "type=text"
  },
  {
    "field": "address",
    "itemname": "地址",
    "type": "text",
    " maxlength": "100",
    "isnull": "true",
    "islist": "",
    "default": "",
    "fieldget": 1,
    "fieldset": 1,
	"limit": 4,
    "inputtype": "address",
    "attr": ""
  }
]


youbang_addoncommodities 表字自动填充字段配置信息:
[
    {
        "field": "componentid",
        "itemname": "组件id",
        "type": "int",
        "maxlength": "10",
        "isnull": true,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 1,
        "inputtype": "input",
        "attr": " disabled data-def=4 data-comment=如：这是注释"
    },
    {
        "field": "title",
        "itemname": "标题",
        "type": "text",
        "maxlength": "25",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": "data-comment=标题长度最多15个字符"
    },
    {
        "field": "classify",
        "itemname": "商品分类",
        "type": "text",
        "maxlength": "1024",
        "isnull": false,
        "islist": "商品分类",
        "default": 0,
        "fieldget": 0,
        "fieldset": 0,
        "novaild": 0,
        "inputtype": "nesmodal"
    },
    {
        "field": "litpic",
        "itemname": "缩略图",
        "type": "text",
        "maxlength": 0,
        "isnull": true,
        "islist": "",
        "default": "",
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": "data-comment=缩略图，限1张"
    },
    {
        "field": "mainpic",
        "itemname": "商品主图",
        "type": "text",
        "maxlength": 0,
        "isnull": true,
        "islist": "",
        "default": "",
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "uploader",
        "limit": 5,
        "attr": "data-comment=端口主图，最多5张"
    },
    {
        "field": "usespec",
        "itemname": "是否启用规格",
        "maxlength": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "spec",
        "attr": "data-comment=是否使用自定义商品规格"
    },
    {
        "field": "spec",
        "itemname": "商品规格",
        "maxlength": 0,
        "fieldget": 1,
        "fieldset": 0,
        "novaild": 0,
        "inputtype": "spec",
        "attr": "data-comment=填写商品分类"
    },
    {
        "field": "body",
        "itemname": "详情内容",
        "type": "text",
        "maxlength": 0,
        "isnull": true,
        "islist": "",
        "default": "",
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 1,
        "inputtype": "uediter",
        "attr": "data-comment=端口详情内容"
    }
]


youbang_addonjobwanted 表字自动填充字段配置信息:
[
    {
        "field": "componentid",
        "itemname": "组件id",
        "type": "int",
        "maxlength": "10",
        "isnull": true,
        "islist": "",
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 1,
        "inputtype": "input",
        "attr": " disabled data-def=4 data-comment=如：这是注释"
    },
    {
        "field": "title",
        "itemname": "标题",
        "type": "text",
        "maxlength": "25",
        "isnull": false,
        "islist": 0,
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": "data-comment=标题长度最多15个字符"
    },
    {
        "field": "uname",
        "itemname": "姓名",
        "type": "text",
        "maxlength": "20",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "limit": 4,
        "novaild": 0,
        "inputtype": "input",
        "attr": " data-comment=如：这是注释"
    },
    {
        "field": "litpic",
        "itemname": "头像",
        "type": "text",
        "maxlength": "255",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "limit": 1,
        "novaild": 0,
        "inputtype": "uploader",
        "attr": " data-def=1 data-comment=如：这是注释"
    },
    {
        "field": "gender",
        "itemname": "性别",
        "type": "varchar",
        "maxlength": "2",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "radio",
        "attr": " data-val='男-女' data-key='0-1' data-def=0 data-comment=如：这是注释"
    },
    {
        "field": "job_experience",
        "itemname": "求职者经验",
        "type": "varchar",
        "maxlength": "11",
        "isnull": false,
        "islist": "求职者经验",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " data-comment=如：这是注释"
    },
    {
        "field": "age",
        "itemname": "年龄",
        "type": "int",
        "maxlength": "2",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=number data-comment=如：这是注释"
    },
    {
        "field": "classify",
        "itemname": "职位",
        "type": "int",
        "effect": "main",
        "maxlength": "7",
        "isnull": false,
        "islist": "职位分类",
        "default": 0,
        "fieldget": 0,
        "fieldset": 0,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " type=text data-comment=如：这是注释"
    },
    {
        "field": "job_salary",
        "itemname": "期望薪资",
        "type": "int",
        "maxlength": "7",
        "isnull": false,
        "islist": "期望薪资",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " type=number data-comment=如：这是注释"
    },
    {
        "field": "job_industry",
        "itemname": "从事行业",
        "type": "varchar",
        "maxlength": "128",
        "isnull": false,
        "islist": "从事行业",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " type=text data-comment=如：这是注释"
    },
    {
        "field": "job_Nature",
        "itemname": "工作性质",
        "type": "varchar",
        "maxlength": "128",
        "isnull": false,
        "islist": "工作性质",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " type=text data-comment=如：这是注释"
    },
    {
        "field": "phone",
        "itemname": "联系电话",
        "type": "int",
        "maxlength": "7",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=tell data-comment=如：这是注释"
    },
    {
        "field": "address",
        "itemname": "期望工作城市",
        "type": "int",
        "maxlength": "11",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "limit": 3,
        "inputtype": "address",
        "attr": " data-comment=如：这是注释"
    },
	{
        "field": "company",
        "itemname": "公司名称",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "32",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " data-comment=填写曾经工作过的公司名称"
    },
	{
        "field": "position",
        "itemname": "职位",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "32",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " data-comment=填写曾经工作中的职位"
    },
	{
        "field": "salary",
        "itemname": "薪资",
        "type": "float",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "11",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=number data-comment=填写曾经工作时的薪资"
    },
	{
        "field": "jobtime",
        "itemname": "在职时间",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "36",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=text data-comment=填写格式如:2018年1月1-2019年12年31日"
    },
	{
        "field": "duty",
        "itemname": "工作职责",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "11",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=text data-comment=填写曾经工作中的职责"
    },
	{
        "field": "city",
        "itemname": "工作地点",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "11",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "novaild": 0,
		"limit": 4,
        "inputtype": "input",
        "attr": " data-comment=填写曾经工作的地点"
    },
	{
        "field": "brightspot",
        "itemname": "我的亮点",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "255",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "novaild": 0,
		"inputtype": "textarea",
        "attr": " data-comment=填写曾经工作中的亮点"
    }
]
youbang_addonperrecruit 表字自动填充字段配置信息:
[
    {
        "field": "classify",
        "itemname": "招聘类型",
        "type": "varchar",
        "maxlength": "64",
        "effect": "main",
        "isnull": true,
        "islist": "招聘类型",
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " data-comment=请选择招聘类型"
    },
    {
        "field": "title",
        "itemname": "招聘标题",
        "type": "varchar",
        "maxlength": "64",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " data-comment=请填写招聘信息"
    },
    {
        "field": "classsalary",
        "itemname": "薪资等级",
        "type": "varchar",
        "maxlength": "64",
        "isnull": false,
        "islist": "薪资分类",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " data-comment=选择薪资所等级"
    },
    {
        "field": "classlabel",
        "itemname": "标签分类",
        "type": "varchar",
        "maxlength": "64",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "checkbox",
        "attr": " data-val=五险一金-包住-包餐 data-key=xj-bz-bc data-comment=选择俱有的特点"
    },
    {
        "field": "classlabel",
        "itemname": "招聘人数",
        "type": "varchar",
        "maxlength": "64",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=number data-comment=填写最多招聘多少人"
    },
    {
        "field": "classexperience",
        "itemname": "经验",
        "type": "varchar",
		"effect": "tab_youbang_jobexperience",
        "maxlength": "64",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " data-comment=填写最多招聘多少人"
    },
    {
        "field": "classeducation",
        "itemname": "最学历要求",
        "type": "varchar",
        "maxlength": "64",
        "isnull": false,
        "islist": "学历分类",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "nesmodal",
        "attr": " data-comment=选择最低学历要求"
    },
    {
        "field": "description",
        "itemname": "职位描述",
        "type": "varchar",
        "maxlength": "255",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "uediter",
        "attr": " data-comment=填写职位要求"
    },
    {
        "field": "level",
        "itemname": "阅读要求",
        "type": "varchar",
        "maxlength": "255",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 1,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=number data-comment=要求不低于等级的用户可以查看信息"
    },
    {
        "field": "mid",
        "itemname": "发布者id",
        "type": "int",
        "maxlength": "11",
        "isnull": false,
        "islist": "",
        "default": 0,
        "fieldget": 0,
        "fieldset": 1,
        "novaild": 0,
        "inputtype": "input",
        "attr": " type=number data-comment=要求不低于等级的用户可以查看信息"
    }
]