
//youbang_addoninfos 表数据采集字段：
//componentid,arcrank,mid,click,title,litpic,userip,senddate,flag,lastpost,scores,goodpost,badpost,nativeplace,infotype,body,endtime,tel,email,linkman,address
//youbang_addoninfos 表字自动填充字段配置信息：
[
  {
    "field": "componentid",
    "itemname": "组件id",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": " disabled data-def=4 data-comment=如：这是注释"
  },
  {
    "field": "arcrank",
    "itemname": "受权浏览",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "5",
    "page": "",
    "attr": "type=number checked disabled"
  },
  {
    "field": "mid",
    "itemname": "会员id",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "8",
    "page": "",
    "attr": "type=number disabled "
  },
  {
    "field": "click",
    "itemname": "点击",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=number disabled "
  },
  {
    "field": "title",
    "itemname": "标题",
    "autofield": "0",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "60",
    "page": "",
    "attr": "type='text'"
  },
  {
    "field": "litpic",
    "itemname": "缩略图",
    "autofield": "0",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "60",
    "page": "",
    "attr": "type=text"
  },
  {
    "field": "userip",
    "itemname": "会员IP",
    "autofield": "0",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "0",
    "default": "0",
    "maxlength": "15",
    "page": "",
    "attr": "type=text disabled"
  },
  {
    "field": "senddate",
    "itemname": "发布时间",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=datetime"
  },
  {
    "field": "flag",
    "itemname": "推荐属性",
    "autofield": "0",
    "notsend": "0",
    "type": "checkbox",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=checkbox data-key=hot-home-recomend data-val=热点-首页-推荐"
  },
  {
    "field": "lastpost",
    "itemname": "最后评论时间",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=datetime disabled"
  },
  {
    "field": "scores",
    "itemname": "评论积分",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "8",
    "page": "",
    "attr": "type=number disabled"
  },
  {
    "field": "goodpost",
    "itemname": "好评数",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "8",
    "page": "",
    "attr": "type=number disabled"
  },
  {
    "field": "badpost",
    "itemname": "差评数",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "8",
    "page": "",
    "attr": "type=number disabled"
  },
  {
    "field": "nativeplace",
    "itemname": "地区",
    "autofield": "1",
    "notsend": "0",
    "type": "stepselect",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "250",
    "page": "",
    "attr": "data-key=area1-area2-area3 data-val=城市1-城市2-城市3"
  },
  {
    "field": "infotype",
    "itemname": "信息类型",
    "autofield": "1",
    "notsend": "0",
    "type": "stepselect",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "250",
    "page": "",
    "attr": ""
  },
  {
    "field": "body",
    "itemname": "信息内容",
    "autofield": "1",
    "notsend": "0",
    "type": "htmltext",
    "isnull": "true",
    "islist": "0",
    "default": "",
    "maxlength": "250",
    "page": "",
    "attr": "type=text"
  },
  {
    "field": "endtime",
    "itemname": "截止日期",
    "autofield": "1",
    "notsend": "0",
    "type": "datetime",
    "isnull": "true",
    "islist": "1",
    "default": "",
    "maxlength": "250",
    "page": "",
    "attr": "type=datetime"
  },
  {
    "field": "tel",
    "itemname": "联系电话",
    "autofield": "1",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "0",
    "default": "",
    "maxlength": "50",
    "page": "",
    "attr": "type=tel"
  },
  {
    "field": "email",
    "itemname": "电子邮箱",
    "autofield": "1",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "0",
    "default": "",
    "maxlength": "50",
    "page": "",
    "attr": "type=email"
  },
  {
    "field": "linkman",
    "itemname": "联系人",
    "autofield": "1",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "0",
    "default": "",
    "maxlength": "50",
    "page": "",
    "attr": "type=text"
  },
  {
    "field": "address",
    "itemname": "地址",
    "autofield": "1",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "0",
    "default": "",
    " maxlength": "100",
    "page": "",
    "attr": "type=address"
  }
]


youbang_addoncommodities 表数据采集字段：
componentid,arcrank,mid,click,userip,senddate,flag,lastpost,scores,body
youbang_addoninfos 表字自动填充字段配置信息：
[
  {
    "field": "componentid",
    "itemname": "组件id",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": " disabled data-def=4 data-comment=如：这是注释"
  },
  {
    "field": "arcrank",
    "itemname": "受权浏览",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "5",
    "page": "",
    "attr": "type=number checked disabled"
  },
  {
    "field": "mid",
    "itemname": "会员id",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "8",
    "page": "",
    "attr": "type=number disabled "
  },
  {
    "field": "click",
    "itemname": "点击",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=number disabled "
  },
  {
    "field": "title",
    "itemname": "标题",
    "autofield": "0",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "60",
    "page": "",
    "attr": "type='text'"
  },
  {
    "field": "userip",
    "itemname": "会员IP",
    "autofield": "0",
    "notsend": "0",
    "type": "text",
    "isnull": "true",
    "islist": "0",
    "default": "0",
    "maxlength": "15",
    "page": "",
    "attr": "type=text disabled"
  },
  {
    "field": "senddate",
    "itemname": "发布时间",
    "autofield": "0",
    "notsend": "0",
    "type": "int",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=datetime"
  },
  {
    "field": "flag",
    "itemname": "推荐属性",
    "autofield": "0",
    "notsend": "0",
    "type": "checkbox",
    "isnull": "true",
    "islist": "1",
    "default": "0",
    "maxlength": "10",
    "page": "",
    "attr": "type=checkbox data-key=hot-home-recomend data-val=热点-首页-推荐"
  },
]